// eGalaxy_Vue/src/components/course_list.vue
<template lang="html">
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="well" style="color:brown">
            <h3>List of Courses</h3>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Author</th>
                    <th>Descrption</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for = "course in courses" :key = "course.Author">
                    <td>{{course.courseName}}</td>
                    <td>{{course.courseAuthor}}</td>
                    <td>{{course.courseDiscription}}</td>
                    <td>{{course.coursePrice | currency }}</td>
                    <td><button  @click = "deleteCourse(course.id)" class="btn btn-danger">Delete</button>
                        <button  @click = "updateCourse(course.id)" class="btn btn-warning" style="margin-left: 10px">Update</button>
                        <button  @click = "courseDetails(course.id)" class="btn btn-success" style="margin-left: 10px">Details</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
  
</template>

<script lang="js">
  import CourseService from '../services/CourseService';
  export default  {
    name: 'test',
    props: [],
    mounted () {
    },
    
    data () {
      return {
          courses: {}
      }
    },
    created()
    {
      //this.courseList();
    },
    beforeMount()
    {
      this.courseList();
    },
    methods: {
      courseDetails(id)
      {
        this.$router.push({name :'courseDetails', params:{id : id}})
      },
      updateCourse(id)
      {
        this.$router.push({name :'updateCourse', params:{id : id}})
      },
      deleteCourse(id)
      {
        CourseService.deleteCourse(id)
        .then(response => {console.log(response.data);
          this.courseList();
        }); 
      },
      courseList()
      {
        console.log("in course list");
        CourseService.getCourses().then(response => {
             this.courses = response.data
         });
      }

    },
    computed: {

    }
}


</script>

<style scoped>
 
</style>

// eGalaxy/src/app/course-list/course-list.component.ts
import { CourseService } from '../course.service';
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';
import { Course } from '../course';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
//import {MatSort, MatSortable, MatTableDataSource} from '@angular/material';



@Component({
  selector: 'app-course-list',
  templateUrl: './course-list.component.html',
  styleUrls: ['./course-list.component.css']
})
export class CourseListComponent implements OnInit 
{
  @ViewChild(MatSort , {static: false}) sort : MatSort;
  columnsName = ['courseName', 'courseAuthor', 'courseDescription', 'coursePrice', 'Action'];
  dataSource;
  courses: Observable<Course[]>;

  constructor(private courseService: CourseService,
    private router: Router) 
    {

    }

  ngOnInit(): void 
  {
    this.reloadData();
  }

  reloadData() {
    //this.courses = this.courseService.getCoursesList();
     this.courseService.getCoursesList()
       .subscribe(result =>
         {
          console.log(result),
          this.dataSource = new MatTableDataSource(result);
          this.dataSource.sort = this.sort;
         });

           
  }

  deleteCourse(id: number)
  {
    this.courseService.deleteCourse(id)
    .subscribe(
      data => {
        console.log(data);
        this.reloadData();
      },
      error => console.log(error));
  }

  courseDetails(id: number)
  {
    console.log("id: " + id);
    this.router.navigate(['details',id]);
  }mvn 

  updateCourse(id: number){
    this.router.navigate(['update', id]);
  }
}

<div class = "data-table">
    <mat-table  class = "table table-striped table-dark" [dataSource] = "dataSource"  matSort>
        <ng-container matColumnDef = "courseName">
            <mat-header-cell *matHeaderCellDef mat-sort-header>Name</mat-header-cell>
            <mat-cell *matCellDef = "let course">{{course.courseName}}</mat-cell>
        </ng-container>
        <ng-container matColumnDef = "courseAuthor">
            <mat-header-cell *matHeaderCellDef mat-sort-header>Author</mat-header-cell>
            <mat-cell *matCellDef = "let course">{{course.courseAuthor}}</mat-cell>
        </ng-container>
        <ng-container matColumnDef = "courseDescription">
            <mat-header-cell *matHeaderCellDef mat-sort-header>Description</mat-header-cell>
            <mat-cell *matCellDef = "let course">{{course.courseDescription}}</mat-cell>
        </ng-container>
        <ng-container matColumnDef = "coursePrice" >
            <mat-header-cell *matHeaderCellDef mat-sort-header>Price</mat-header-cell>
            <mat-cell *matCellDef = "let course">{{course.coursePrice | currency:'INR' }}</mat-cell>
        </ng-container>
        <ng-container matColumnDef = "Action">
                <mat-header-cell *matHeaderCellDef [ngClass]="'customWidthClass'">Action</mat-header-cell>
        <mat-cell *matCellDef="let course"[ngClass]="'customWidthClass'" > 
            <button (click)="deleteCourse(course.id)" class="btn btn-danger">Delete</button>
                        <button (click)="updateCourse(course.id)" class="btn btn-warning" style="margin-left: 10px">Update</button>
                        <button (click)="courseDetails(course.id)" class="btn btn-success" style="margin-left: 10px">Details</button>
        </mat-cell>        
        </ng-container>
        <mat-header-row *matHeaderRowDef="columnsName" color="primary"></mat-header-row>
        <mat-row *matRowDef = "let row; columns:columnsName"></mat-row>
    </mat-table>
</div>
